---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: |
      #!/bin/bash
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      npm install
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: CF_INSTANCES
    value: '1'
    type: text
  - name: CF_MEMORY
    value: 128M
    type: text
  - name: CONVERSATION_SERVICE_NAME
    value: 'Bot Asset Exchange Workspaces'
    type: text
  - name: WORKSPACE_NAME
    value: 'ThinkFriday Chatbot'
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      #set -x
      #CF_TRACE=true

      if ! cf service "${CONVERSATION_SERVICE_NAME}" ; then
        cf create-service conversation free "${CONVERSATION_SERVICE_NAME}"
      fi

      # uploads app to ibm cloud (without starting the app)
      cf push $CF_APP -i ${CF_INSTANCES} -m ${CF_MEMORY} --no-start

      # sets vcap and costum-env
      cf bind-service $CF_APP "${CONVERSATION_SERVICE_NAME}"
      cf set-env $CF_APP WORKSPACE_NAME "${WORKSPACE_NAME}"
      
      # start app with environemt
      cf start $CF_APP

      # View logs
      #cf logs "${CF_APP}" --recent
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api-integration.ng.bluemix.net/v1/messaging/webhook/publish
